laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImageController;
use App\Models\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home')->with('imageCollection', Image::all());
});

Route::get('/home', function () {
    return view('home')->with('imageCollection', Image::all());
});

Route::resource('image', ImageController::class);
Route::post('/image-update/{id}', [ImageController::class, 'update'])->name('imageUpdate');
Route::post('/category', [ImageController::class, 'createImageCategory'])->name('createCategory');
Route::get('/image-destroy/{id}', [ImageController::class, 'destroy'])->name('imageDestroy');
Route::get('/image-destroy-all', [ImageController::class, 'destroyAll'])->name('imageDestroyAll');
Route::get('/load', [ImageController::class, 'loadFirstImages'])->name('loadImages');

laravel/resources/views/create_image.blade.php
@extends('layouts.app')

@section('title', 'Crear imagen')

@section('content')

 
               
        <div class="row">
            <div class="col-md-7 offset-md-2">    
                @if($errors->has('fail'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('fail')}}</b></p>
                        </div>
                    </div>    
                @elseif($errors->has('successfull'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-success' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('successfull')}}</b></p>
                        </div>
                    </div>    
                @endif
            </div>   
        </div>   
    
    <div class=row>
        <div class="col-md-7 offset-md-2">
        <form id="form_create" method="POST" action="{{route('image.store')}}" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="title">Título de la imagen:</label>
                <input id="form_create_image_title" type="text" class="form-control" name="title" value="" required="required"/>
            </div>
            @if($errors->has('title'))
            <div class="row">
                <div class="col-md-7 offset-md-2">
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 15px;text-align: center'><b>{{$errors->first('title')}}</b></p>
                        </div>
                    </div>
                </div>
            </div>        
            @endif        
            <div class="form-group row">
                <div class="col-md-7">
                    <label for="category">Categoría de la imagen:</label>
                    <select id="form_create_image_category" class="form-control" name="category">
                        @foreach($categories as $category)
                            @if($loop->index == 0)
                                <option selected="selected" value="{{$category->name}}">{{$category->name}}</option>
                            @else
                                <option value="{{$category->name}}">{{$category->name}}</option>
                            @endif       
                        @endforeach
                    </select>
                </div> 
                <div class="col-md-3 offset-2">
                    <button id="btn-modal-category" type="button" class="btn btn-primary" data-toggle="modal" data-target="#categoryModal">
                        Crear categoría
                    </button>
                </div>       
            </div>
            @if($errors->has('category'))
                <div class="row">
                    <div class="col-md-7 offset-md-2">
                        <div class='col-md-12 form_alert'>
                            <div>
                                <p class='alert alert-danger' role='alert' style='font-size: 15px;text-align: center'><b>{{$errors->first('category')}}</b></p>
                            </div>
                        </div>
                    </div>
                </div> 
            @endif    
                               
            <div class="form-group">
                <label for="description">Descripción de la imagen:</label>
                <textarea id="form_create_image_description" class="form-control" name="description" rows="3" required="required"></textarea>
            </div>
            <div class="form-group">
                <label for="url">Imagen:</label>
                <input id="form_create_image_file" type="file" class="form-control-file load_image_file" name="url" required="required">

            </div>
            <div class="form-group row">
                <div class="col-md-5">
                    <img src="" alt="" class="img-thumbnail form_image_preview"> 
                </div>    
            </div>
            @if($errors->has('incorrect_format'))
                <div class="row">
                    <div class="col-md-7 offset-md-2">
                        <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 15px;text-align: center'><b>{{$errors->first('incorrect_format')}}</b></p>
                        </div>
                        </div>
                    </div>
                </div>  
            @endif
            <div class="row">
                <div class="col-md-4 col-sm-12 col-xs-12 offset-md-4">
                    <a href="{{route('image.index')}}" class="form-control btn btn-outline-dark btn-group-actions">Listado de imágenes</a> 
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <input type="submit" id="create_image" value="Crear" class="form-control btn btn-primary btn-group-actions"/> 
                </div>
            </div>

            
                       
        </form>
        </div>
    </div>    

    @include('modal')

@endsection

laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Image CRUD')


@section('content')
        <div id="content_section">   
           @if(isset($response))
            <div class="row">
                <div class="col-md-7 offset-md-2">
                    <div class='col-md-12 form_alert'>
                        <p class='alert alert-secondary' role='alert' style='font-size: 15px;text-align: center'><b>{{$response}}</b></p>
                    </div>
                </div>
            </div>
            @endif

            <div class="card-columns">
                @if(count($imageCollection) == 0)
                <div class="row">
                    <div class="col-md-12 offset-md-10">
                        <h1 class="no_images">No hay imágenes insertadas</h1>
                    </div>
                    </div>    
                @endif
                @foreach($imageCollection as $image)
                
                        <div id="{{$loop->index}}" class="card" ttle="{{$image->title}}">
                            <img src="{{$image->url}}" class="card-img-top img-fluid" alt="{{$image->title}}">
                            <div class="card-body">
                                <p class="card-text"><span class="text-muted">{{$image->category()->first()->name}}</span></p>
                                <h5 class="card-title">{{$image->title}}</h5>
                            </div>
                            <div class="card-footer">
                                <div class="btn-group" role="group" aria-label="Action buttons">
                                    <a href="{{route('image.show', [$image->id])}}" class="btn btn-primary btn-sm"><i class="material-icons">visibility</i></a>
                                    <a href="{{route('image.edit', [$image->id])}}" class="btn btn-light btn-sm"><i class="material-icons">create</i></a>
                                    <a href="{{route('imageDestroy', [$image->id])}}" onclick="return confirm('¿Está seguro que desea eliminar la imagen?')" class="btn btn-danger btn-sm"><i class="material-icons">delete_outline</i></a>
                                </div>
                            </div>    
                        </div>
                        
                       
                @endforeach    
            </div>
        </div>
        
@endsection

  

laravel/resources/views/image_detail.blade.php
@extends('layouts.app')

@section('title', 'Detalles de la imagen')

@section('content')

    <div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-md-5">
        <img src={{$image->url}} class="card-img" alt={{$image->title}}>
        </div>
        <div class="col-md-7">
        <div class="card-body">
            <h2 class="card-title">{{$image->title}}</h2>
            <h4 class="card-text">{{$image->category()->first()->name}}</h4>
            <p class="card-text">{{$image->description}}</p>
            
        </div>
        </div>
    </div>
    </div>
    
    <div class="row">
        <div class="col-md-3 col-sm-12 col-xs-12 offset-md-5">
            <a href="{{route('image.index')}}" class="btn btn-outline-dark detail-back">Listado de imágenes</a>
        </div>        
    </div>

@endsection

laravel/resources/views/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="categoryModalLabel">Crear categoría de imagen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <div id="div_form_category_msg" class="row">
    
      </div>     

        <form id="form_create_category" method="POST" action="javascript::void(0)" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="name">Nombre de la categoría:</label>
                <input id="form_create_category_name" type="text" class="form-control" name="name" value="" required="required"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <input type="submit" class="btn btn-primary" value="Crear"/>
            </div>
        </form>        
      </div>
      
    </div>
  </div>
</div>

laravel/resources/views/update_image.blade.php
@extends('layouts.app')

@section('title', 'Modificar imagen')

@section('content')

    <div class="row">
        <div class="col-md-7 offset-md-2">
            <div id="div_form_update_image">
                @if($errors->has('image_category'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('image_category')}}</b></p>
                        </div>
                    </div>
                @elseif($errors->has('image_title'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('image_title')}}</b></p>
                        </div>
                    </div>
                @elseif($errors->has('incorrect_format'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('incorrect_format')}}</b></p>
                        </div>
                    </div>
                @elseif($errors->has('fail'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-danger' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('fail')}}</b></p>
                        </div>
                    </div>    
                @elseif($errors->has('successfull'))
                    <div class='col-md-12 form_alert'>
                        <div>
                            <p class='alert alert-success' role='alert' style='font-size: 20px;text-align: center'><b>{{$errors->first('successfull')}}</b></p>
                        </div>
                    </div>    
                @endif
            </div>   
        </div>   
    </div>
    <div class=row>
        <div class="col-md-7 offset-md-2">
        <form id="form_update" method="POST" action="{{route('imageUpdate', $image->id)}}" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="image_title">Título de la imagen:</label>
                <input id="form_update_image_title" type="text" class="form-control" name="image_title" value="{{$image->title}}"/>
            </div>
            <div class="form-group">
                <label for="image_category">Categoría de la imagen:</label>
                <select id="form_update_image_category" class="form-control" name="image_category">
                    @foreach($categories as $category)
                        @if($category->id == $image->category_id)
                            <option selected="selected" value="{{$category->name}}">{{$category->name}}</option>
                        @else    
                            <option value="{{$category->name}}">{{$category->name}}</option>
                        @endif        
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="image_description">Descripción de la imagen:</label>
                <textarea id="form_update_image_description" class="form-control" name="image_description" rows="3">{{$image->description}}</textarea>
            </div>
            <div class="form-group">
                <label for="image_file">Imagen:</label>
                <input id="form_update_image_file" type="file" class="form-control-file load_image_file" name="image_file">

            </div>
            <div class="form-group row">
                <div class="col-md-5">
                    <img src="{{$image->url}}" alt="{{$image->title}}" class="img-thumbnail form_image_preview"> 
                </div>    
            </div> 
            
            <div class="row">
                <div class="col-md-4 col-sm-12 col-xs-12 offset-md-4">
                    <a href="{{route('image.index')}}" class="form-control btn btn-outline-dark btn-group-actions">Listado de imágenes</a> 
                </div>
                <div class="col-md-4 col-sm-12 col-xs-12 ">
                    <input type="submit" id="update_image" value="Modificar" class="form-control btn btn-primary btn-group-actions"/> 
                </div>
            </div>

            
                       
        </form>
        </div>
    </div>    


@endsection